export const SKILLS_DICTIONARY = [
  // Tech, Programming & Data
  { name: 'JavaScript', category: 'Tech' },
  { name: 'TypeScript', category: 'Tech' },
  { name: 'React', category: 'Tech' },
  { name: 'Next.js', category: 'Tech' },
  { name: 'Vue', category: 'Tech' },
  { name: 'Angular', category: 'Tech' },
  { name: 'Node.js', category: 'Tech' },
  { name: 'Python', category: 'Tech' },
  { name: 'Java', category: 'Tech' },
  { name: 'Spring Boot', category: 'Tech' },
  { name: 'PHP', category: 'Tech' },
  { name: 'Laravel', category: 'Tech' },
  { name: 'C#', category: 'Tech' },
  { name: '.NET', category: 'Tech' },
  { name: 'Go', category: 'Tech' },
  { name: 'Rust', category: 'Tech' },
  { name: 'SQL', category: 'Tech' },
  { name: 'PostgreSQL', category: 'Tech' },
  { name: 'MongoDB', category: 'Tech' },
  { name: 'AWS', category: 'Tech' },
  { name: 'Azure', category: 'Tech' },
  { name: 'Google Cloud', category: 'Tech' },
  { name: 'Docker', category: 'Tech' },
  { name: 'Kubernetes', category: 'Tech' },
  { name: 'DevOps', category: 'Tech' },
  { name: 'Cybersecurity', category: 'Tech' },
  { name: 'Data Engineering', category: 'Tech' },
  { name: 'Machine Learning', category: 'Tech' },
  { name: 'Artificial Intelligence', category: 'Tech' },

  // BPO & Customer Operations
  { name: 'Customer Service', category: 'BPO' },
  { name: 'Technical Support', category: 'BPO' },
  { name: 'Inbound Calls', category: 'BPO' },
  { name: 'Outbound Sales', category: 'BPO' },
  { name: 'Chat Support', category: 'BPO' },
  { name: 'Email Support', category: 'BPO' },
  { name: 'Back Office', category: 'BPO' },
  { name: 'Quality Assurance', category: 'BPO' },
  { name: 'Virtual Assistant', category: 'BPO' },
  { name: 'Data Entry', category: 'BPO' },

  // Finance & Accounting
  { name: 'Accounting', category: 'Finance' },
  { name: 'CPA', category: 'Finance' },
  { name: 'Bookkeeping', category: 'Finance' },
  { name: 'Accounts Payable', category: 'Finance' },
  { name: 'Accounts Receivable', category: 'Finance' },
  { name: 'Financial Analysis', category: 'Finance' },
  { name: 'Audit', category: 'Finance' },
  { name: 'Tax Compliance', category: 'Finance' },
  { name: 'QuickBooks', category: 'Finance' },
  { name: 'Xero', category: 'Finance' },
  { name: 'SAP', category: 'Finance' },

  // Marketing, Creative & Content
  { name: 'Digital Marketing', category: 'Marketing' },
  { name: 'SEO', category: 'Marketing' },
  { name: 'Social Media Management', category: 'Marketing' },
  { name: 'Content Writing', category: 'Marketing' },
  { name: 'Copywriting', category: 'Marketing' },
  { name: 'Graphic Design', category: 'Design' },
  { name: 'UI/UX Design', category: 'Design' },
  { name: 'Figma', category: 'Design' },
  { name: 'Adobe Creative Suite', category: 'Design' },
  { name: 'Video Editing', category: 'Design' },

  // HR, Management & Admin
  { name: 'Recruitment', category: 'HR' },
  { name: 'Employee Relations', category: 'HR' },
  { name: 'Payroll', category: 'HR' },
  { name: 'Project Management', category: 'Management' },
  { name: 'Agile', category: 'Management' },
  { name: 'Scrum', category: 'Management' },
  { name: 'Business Analysis', category: 'Management' },
  { name: 'Sales Operations', category: 'Management' },

  // Healthcare & Engineering
  { name: 'Registered Nurse', category: 'Healthcare' },
  { name: 'Medical Transcription', category: 'Healthcare' },
  { name: 'Pharmacist', category: 'Healthcare' },
  { name: 'Civil Engineering', category: 'Engineering' },
  { name: 'Electrical Engineering', category: 'Engineering' },
  { name: 'Mechanical Engineering', category: 'Engineering' },
  { name: 'Autocad', category: 'Engineering' },
];